((lang) => {
  lang['en'] = {
    language: 'Language',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    pageHeading: 'COVID-19 CORONAVIRUS OUTBREAK',
    refreshAfter: 'Refresh After(second)',
    coronavirusCases: 'Coronavirus Cases',
    recovered: 'Recovered',
    deaths: 'Deaths',
    SearchByCountry: 'Search By Country',
    totalCases: 'Total Cases',
    todayCases: 'Today Cases',
    todayDeaths: 'Today Deaths',
    recovered: 'Recovered',
    Vietnam: 'Viet Nam',
    global: 'Global',
    timeInfo: 'Data was based on UTC time zone, Last updated on',
    active: 'Active',
    critical: 'Critical',
    continent: 'Continent',
    all: 'All',
    'North America': 'North America',
    'South America': 'South America',
    Asia: 'Asia',
    Europe: 'Europe',
    Africa: 'Africa',
    'Australia/Oceania': 'Australia/Oceania',
  };
})((window._lang = window._lang || {}));
